version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  version: 2
  test:
    jobs:
      - build-test-linux:
          name: .NET 7.0 - Linux
          docker-image: mcr.microsoft.com/dotnet/sdk:7.0
          build-target-framework: netstandard2.0
          test-target-framework: net7.0
      - build-test-windows:
          name: .NET Framework 4.6.2 - Windows
          build-target-framework: net462
          test-target-framework: net462

jobs:
  build-test-linux:
    parameters:
      docker-image:
        type: string
      build-target-framework:
        type: string
      test-target-framework:
        type: string
    docker:
      - image: <<parameters.docker-image>>
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      BUILDFRAMEWORKS: <<parameters.build-target-framework>>
      TESTFRAMEWORK: <<parameters.test-target-framework>>
    steps:
      - checkout
      - run:
          name: restore dependencies
          command: dotnet restore src/LaunchDarkly.Logging.CommonLogging
      - run:
          name: build
          command: dotnet build src/LaunchDarkly.Logging.CommonLogging
      - run:
          name: run tests
          command: dotnet test test/LaunchDarkly.Logging.CommonLogging.Tests

  build-test-windows:
    parameters:
      build-target-framework:
        type: string
      test-target-framework:
        type: string
    executor:
      name: win/default
      shell: powershell.exe
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      BUILDFRAMEWORKS: <<parameters.build-target-framework>>
      TESTFRAMEWORK: <<parameters.test-target-framework>>
    steps:
      - checkout
      - run:
          name: restore dependencies
          command: dotnet restore src/LaunchDarkly.Logging.CommonLogging
      - run:
          name: build
          command: dotnet build src/LaunchDarkly.Logging.CommonLogging
      - run:
          name: run tests
          command: dotnet test test/LaunchDarkly.Logging.CommonLogging.Tests
