
publications:
  - url: https://nuget.org/packages/LaunchDarkly.Logging.CommonLogging
    description: NuGet

circleci:
  windows:
    context: org-global

template:
  name: dotnet-windows
  env:
    LD_RELEASE_TEST_TARGET_FRAMEWORK: net452
    LD_RELEASE_DOCS_TARGET_FRAMEWORK: net452

documentation:
  title: LaunchDarkly Logging API for .NET - Common.Logging Adapter
  githubPages: true
